# Generated by Django 2.1.2 on 2018-11-30 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='diary',
            name='created',
            field=models.CharField(default=datetime.datetime.now, max_length=256),
        ),
        migrations.AddField(
            model_name='diary',
            name='detail',
            field=models.CharField(default='No content', max_length=1024),
        ),
    ]
